---

networks:
  default:
    external: true
    name: kafka-toolage

#volumes:

services:
  kowl:
    image: quay.io/cloudhut/kowl:v1.5.0
    hostname: kowl
    container_name: kowl
    healthcheck:
      test: wget --spider http://localhost:8080/ || exit 1
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./kowl/config.yaml:/etc/kowl/config.yaml
    ports:
      - "9002:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml


  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    stop_grace_period: 30s
    healthcheck:
      test: curl -s http://localhost:80 || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '8888:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
