{
 "title": "01 - Kafka Connect Cluster - Overview",
 "description": "Monitor Apache Kafka Connect",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{cluster_id=~\"$cluster\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_total_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_metrics{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_metrics{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_metrics{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "timeseries",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_metrics{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_running_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_failed_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_paused_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_destroyed_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_connect_worker_metrics_connector_unassigned_task_count{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "description": "Rebalances average time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_rebalance_avg_time_ms{cluster_type=\"connect\", instance=~\"$instance\",cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Rebalance",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "targets": [
    {
     "expr": " (kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{cluster_type=\"connect\", cluster_type=\"connect\",cluster_id=~\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}