{
 "title": "05 - Kafka Connect Cluster - Worker",
 "description": "Kafka Connect",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{cluster_id=~\"$cluster\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connect Worker",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_connect_app_info{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\",start_time_ms!=\"\"}"
    },
    {
     "expr": "kafka_connect_app_info{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\",version!=\"\"}"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_count{cluster_type=\"connect\", cluster_id=~\"$cluster\",  instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_startup_success_total{cluster_type=\"connect\", cluster_id=~\"$cluster\",  instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_connector_startup_failure_total{cluster_type=\"connect\", cluster_id=~\"$cluster\",  instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_count{cluster_type=\"connect\", cluster_id=~\"$cluster\",  instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_startup_success_total{cluster_type=\"connect\", cluster_id=~\"$cluster\",  instance=~\"$instance\"})"
    },
    {
     "expr": "sum by (instance) (kafka_connect_connect_worker_metrics_task_startup_failure_total{cluster_type=\"connect\", cluster_id=~\"$cluster\",  instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connection_count{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_failed_authentication_total{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Success authentication connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_successful_authentication_rate{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Average number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_request_rate{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_response_rate{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", client_id!=\"\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  }
 ]
}