{
 "title": "06 - Kafka Connect Cluster - Connector Errors",
 "tags": [
  "kafka",
  "connect_cluster"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"connect\", cluster_id=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{cluster_id=~\"$cluster\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total record failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_failures{cluster_type=\"connect\",cluster_id=~\"$cluster\",instance=~\"$instance\",connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_records_skipped{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_errors_logged{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_errors{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_retries{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_deadletterqueue_produce_requests{cluster_type=\"connect\", cluster_id=~\"$cluster\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}