#!/bin/bash

set -e
cd "$(dirname "$0")"
. /scripts/common/config.sh

CLUSTER=oauth
PROTOCOL=plaintext
ADMIN_BOOTSTRAP_SERVER=$CLUSTER-broker-1:9092,$CLUSTER-broker-2:9092,$CLUSTER-broker-3:9092
ADMIN_CONFIG=./config/admin-$PROTOCOL.config

kafka-topics \
  --bootstrap-server $ADMIN_BOOTSTRAP_SERVER \
  --command-config $ADMIN_CONFIG \
  "$@"

