#!/bin/bash

set -e
. /scripts/common/config.sh
cd "$(dirname $0)"

CLUSTER=oauth
PROTOCOL=plaintext
ADMIN_BOOTSTRAP_SERVER=$CLUSTER-broker-1:9092,$CLUSTER-broker-2:9092,$CLUSTER-broker-3:9092
ADMIN_CONFIG=./config/admin-$PROTOCOL.config

if [ $# -gt 0 ] && [ "$1" == "ssl" ]; then
  TOPIC=ssl-perf
  BOOTSTRAP_SERVER=$CLUSTER-broker-1:9093,$CLUSTER-broker-2:9093,$CLUSTER-broker-3:9093
  PRODUCER_CONFIG=./config/producer-ssl.config
else
  TOPIC=plaintext-perf
  BOOTSTRAP_SERVER=$CLUSTER-broker-1:9092,$CLUSTER-broker-2:9092,$CLUSTER-broker-3:9092
  PRODUCER_CONFIG=./config/producer-plaintext.config
fi

kafka-topics \
  --bootstrap-server $ADMIN_BOOTSTRAP_SERVER \
  --command-config $ADMIN_CONFIG \
  --create \
  --if-not-exists \
  --topic $TOPIC \
  --replication-factor 3 \
  --partitions 4

NUM_RECORDS=1000000
RECORD_SIZE=1024


kafka-producer-perf-test \
    --topic $TOPIC \
    --throughput -1 \
    --num-records $NUM_RECORDS \
    --record-size $RECORD_SIZE \
    --producer-props \
        acks=all \
        bootstrap.servers=$BOOTSTRAP_SERVER \
    --producer.config $PRODUCER_CONFIG
