#!/bin/bash

set -e
cd "$(dirname "$0")"
. ./_ssl.sh

CURL="curl -s -k -H Content-Type:application/json -H Accept:application/json -u sr:sr-secret"
HOST=https://ssl-connect:8083

$CURL -X DELETE $HOST/connectors/datagen-pageviews | jq
$CURL -X POST   --data @./connectors/datagen-pageviews.json $HOST/connectors | jq
$CURL -X GET    $HOST/connectors/datagen-pageviews/status | jq

$CURL -X DELETE $HOST/connectors/filesink-pageviews | jq
$CURL -X POST   --data @./connectors/filesink-pageviews.json $HOST/connectors | jq
$CURL -X GET  $HOST/connectors/filesink-pageviews/status | jq
