#!/bin/bash

set -e
. /scripts/common/config.sh
cd "$(dirname $0)"

ADMIN_BOOTSTRAP_SERVER=noauth-broker-1:9092,noauth-broker-2:9092,noauth-broker-3:9092
ADMIN_CONFIG=./config/admin.config

if [ $# -gt 0 ] && [ "$1" == "ssl" ]; then
  TOPIC=ssl-perf
  BOOTSTRAP_SERVER=noauth-broker-1:9093,noauth-broker-2:9093,noauth-broker-3:9093
  CONSUMER_CONFIG=./config/ssl-consumer.config
else
  TOPIC=plaintext-perf
  BOOTSTRAP_SERVER=noauth-broker-1:9092,noauth-broker-2:9092,noauth-broker-3:9092
  CONSUMER_CONFIG=./config/plaintext-consumer.config
fi


kafka-consumer-perf-test \
    --topic $TOPIC \
    --bootstrap-server $BOOTSTRAP_SERVER \
    --messages 3000000 \
    --consumer.config $CONSUMER_CONFIG | jq -R .| jq -sr 'map(./",")|transpose|map(join(": "))[]'


# For better output readability, use jq to transpose the rows and columns
# https://medium.com/metrosystemsro/apache-kafka-how-to-test-performance-for-clients-configured-with-ssl-encryption-3356d3a0d52b