#!/bin/sh

set -e
. /scripts/common/config.sh
cd "$(dirname "$0")"

TOPIC=ssl-perf

CLUSTER=ssl
PROTOCOL=ssl
BOOTSTRAP_SERVER=$CLUSTER-broker-1:9093,$CLUSTER-broker-2:9093,$CLUSTER-broker-3:9093
ADMIN_CONFIG=./config/admin-$PROTOCOL.config
PRODUCER_CONFIG=./config/producer-$PROTOCOL.config
CONSUMER_CONFIG=./config/consumer-$PROTOCOL.config

kafka-console-consumer \
  --bootstrap-server $BOOTSTRAP_SERVER \
  --consumer.config $CONSUMER_CONFIG \
  --from-beginning \
  --topic "$@"

