#!/bin/bash

set -e
cd "$(dirname "$0")"
. ./_noauth.sh


echo "noauth-connect-a"

HOST=http://noauth-connect-a:8083
$CURL -X DELETE $HOST/connectors/a-datagen-pageviews | jq
$CURL -X DELETE $HOST/connectors/a-filesink-pageviews | jq
$CURL -X POST   --data @./connectors/a-datagen-pageviews.json $HOST/connectors | jq
$CURL -X POST   --data @./connectors/a-filesink-pageviews.json $HOST/connectors | jq
$CURL -X GET    $HOST/connectors/a-datagen-pageviews/status | jq
$CURL -X GET    $HOST/connectors/a-filesink-pageviews/status | jq

echo "noauth-connect-b"

HOST=http://noauth-connect-b:8083
$CURL -X DELETE $HOST/connectors/b-datagen-pageviews | jq
$CURL -X DELETE $HOST/connectors/b-filesink-pageviews | jq
$CURL -X POST   --data @./connectors/b-datagen-pageviews.json $HOST/connectors | jq
$CURL -X POST   --data @./connectors/b-filesink-pageviews.json $HOST/connectors | jq
$CURL -X GET    $HOST/connectors/b-datagen-pageviews/status | jq
$CURL -X GET    $HOST/connectors/b-filesink-pageviews/status | jq
