---

networks:
  default:
    external: true
    name: kafka-toolage

volumes:
  zk: {}
  zk_log: {}
  zk_secrets: {}
  bk1: {}
  bk2: {}
  bk3: {}
  sr_secrets: {}
  ct: {}
  ct_secrets: {}

services:

  ssl-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    hostname: ssl-zookeeper
    container_name: ssl-zookeeper
    healthcheck:
      test: echo ruok | nc -w 2 localhost 2181 | grep imok
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - zk:/var/lib/zookeeper/data
      - zk_log:/var/lib/zookeeper/log
      - zk_secrets:/etc/zookeeper/secrets
      - ./jmx_prometheus:/opt/jmx_prometheus
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: >-
        -Dzookeeper.4lw.commands.whitelist=ruok,stat
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/zookeeper-config.yml

  ssl-broker-1:
    image: confluentinc/cp-kafka:7.2.0
    hostname: ssl-broker-1
    container_name: ssl-broker-1
    healthcheck:
      test: nc -z localhost 9093 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      ssl-zookeeper:
        condition: service_healthy
    volumes:
      - bk1:/var/lib/kafka/data
      - ./secrets:/etc/kafka/secrets/
      - ./jmx_prometheus:/opt/jmx_prometheus
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'ssl-zookeeper:2181'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: SSL://ssl-broker-1:9093
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_SSL_KEYSTORE_FILENAME: ssl-broker-1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:CN=root;User:CN=ssl-broker-1;User:CN=ssl-broker-2;User:CN=ssl-broker-3;User:CN=ssl-schema-registry;User:CN=ssl-connect;User:CN=kafka-ui
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
      KAFKA_METRIC_REPORTERS:
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

  ssl-broker-2:
    image: confluentinc/cp-kafka:7.2.0
    hostname: ssl-broker-2
    container_name: ssl-broker-2
    healthcheck:
      test: nc -z localhost 9093 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      ssl-zookeeper:
        condition: service_healthy
    volumes:
      - bk2:/var/lib/kafka/data
      - ./secrets:/etc/kafka/secrets/
      - ./jmx_prometheus:/opt/jmx_prometheus
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'ssl-zookeeper:2181'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: SSL://ssl-broker-2:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
      KAFKA_SSL_KEYSTORE_FILENAME: ssl-broker-2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:CN=root;User:CN=ssl-broker-1;User:CN=ssl-broker-2;User:CN=ssl-broker-3;User:CN=ssl-schema-registry;User:CN=ssl-connect;User:CN=kafka-ui
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
      KAFKA_METRIC_REPORTERS:
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

  ssl-broker-3:
    image: confluentinc/cp-kafka:7.2.0
    hostname: ssl-broker-3
    container_name: ssl-broker-3
    healthcheck:
      test: nc -z localhost 9093 || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      ssl-zookeeper:
        condition: service_healthy
    volumes:
      - bk3:/var/lib/kafka/data
      - ./secrets:/etc/kafka/secrets/
      - ./jmx_prometheus:/opt/jmx_prometheus
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'ssl-zookeeper:2181'
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: SSL://ssl-broker-3:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 500
      KAFKA_SSL_KEYSTORE_FILENAME: ssl-broker-3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_KEY_CREDENTIALS: kafka.key
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.key
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:CN=root;User:CN=ssl-broker-1;User:CN=ssl-broker-2;User:CN=ssl-broker-3;User:CN=ssl-schema-registry;User:CN=ssl-connect;User:CN=kafka-ui
      KAFKA_OPTS: >-
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/kafka-config.yml
      KAFKA_METRIC_REPORTERS:
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      SCHEMA_REGISTRY_AUTHENTICATION_METHOD: "BASIC"
      SCHEMA_REGISTRY_AUTHENTICATION_ROLES: "write,read,admin"
      SCHEMA_REGISTRY_AUTHENTICATION_REALM: "SchemaRegistry"
      SCHEMA_REGISTRY_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/sr_jaas.conf"
      #
#      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
#          username=\"sr\" \
#          password=\"sr-secret\";"

      #SCHEMA_REGISTRY_AUTHENTICATION_ROLES: admin
      #SCHEMA_REGISTRY_AUTHENTICATION_REALM: SchemaRegistry

  ssl-schema-registry:
    image: confluentinc/cp-schema-registry:7.2.0
    hostname: ssl-schema-registry
    container_name: ssl-schema-registry
    stop_grace_period: 120s
    healthcheck:
      test: curl -k --fail -u sr:sr-secret https://localhost:8082/ || exit 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      ssl-broker-1:
        condition: service_healthy
      ssl-broker-2:
        condition: service_healthy
      ssl-broker-3:
        condition: service_healthy
    volumes:
      - sr_secrets:/etc/schema-registry/secrets/
      - ./secrets:/etc/kafka/secrets/
      - ./jmx_prometheus:/opt/jmx_prometheus
    environment:
      SCHEMA_REGISTRY_LISTENERS: https://0.0.0.0:8082
      SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: https
      SCHEMA_REGISTRY_HOST_NAME: ssl-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ssl-broker-1:9093,ssl-broker-2:9093,ssl-broker-3:9093
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/ssl-schema-registry.keystore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: broker_secret
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.server.truststore.jks
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: broker_secret
      KAFKA_METRIC_REPORTERS:
      CONFLUENT_METRICS_ENABLE: 'false'
      SCHEMA_REGISTRY_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka/secrets/sr_jaas.conf
      EXTRA_OPTS: >-
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/sr-config.yml
      SCHEMA_REGISTRY_AUTHENTICATION_METHOD: "BASIC"
      SCHEMA_REGISTRY_AUTHENTICATION_ROLES: "write,read,admin"
      SCHEMA_REGISTRY_AUTHENTICATION_REALM: "SchemaRegistry"
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/ssl-schema-registry.keystore.jks
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: broker_secret
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: broker_secret
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.server.truststore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: broker_secret


  ssl-connect:
    image: confluentinc/cp-kafka-connect:7.2.0
    hostname: ssl-connect
    container_name: ssl-connect
    healthcheck:
      test: curl -k --fail -u sr:sr-secret https://ssl-connect:8083/ || exit 1
      start_period: 15s
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      ssl-broker-1:
        condition: service_healthy
      ssl-broker-2:
        condition: service_healthy
      ssl-broker-3:
        condition: service_healthy
    volumes:
      - ct:/var/lib/kafka/data
      - ct_secrets:/etc/kafka/secrets
      - ./jars:/etc/kafka-connect/jars
      - ./data:/data
      - ./secrets:/etc/kafka-connect/secrets
      - ./jmx_prometheus:/opt/jmx_prometheus
    command:
      - /bin/bash
      - -c
      - |
        confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:latest
        /etc/confluent/docker/run &
        sleep infinity
    environment:
      CONNECT_BOOTSTRAP_SERVERS: ssl-broker-1:9093,ssl-broker-2:9093,ssl-broker-3:9093
      CONNECT_SECURITY_PROTOCOL: SSL
      CONNECT_SSL_KEYSTORE_LOCATION: /etc/kafka-connect/secrets/ssl-connect.keystore.jks
      CONNECT_SSL_KEYSTORE_PASSWORD: broker_secret
      CONNECT_SSL_KEY_PASSWORD: broker_secret
      CONNECT_SSL_TRUSTSTORE_LOCATION: /etc/kafka-connect/secrets/kafka.server.truststore.jks
      CONNECT_SSL_TRUSTSTORE_PASSWORD: broker_secret
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SSL
      CONNECT_PRODUCER_SSL_KEYSTORE_LOCATION: /etc/kafka-connect/secrets/ssl-connect.keystore.jks
      CONNECT_PRODUCER_SSL_KEYSTORE_PASSWORD: broker_secret
      CONNECT_PRODUCER_SSL_KEY_PASSWORD: broker_secret
      CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: /etc/kafka-connect/secrets/kafka.server.truststore.jks
      CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD: broker_secret
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SSL
      CONNECT_CONSUMER_SSL_KEYSTORE_LOCATION: /etc/kafka-connect/secrets/ssl-connect.keystore.jks
      CONNECT_CONSUMER_SSL_KEYSTORE_PASSWORD: broker_secret
      CONNECT_CONSUMER_SSL_KEY_PASSWORD: broker_secret
      CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: /etc/kafka-connect/secrets/kafka.server.truststore.jks
      CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD: broker_secret
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: All
      CONNECT_LISTENERS: https://ssl-connect:8083
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'connect'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_CONFIG_PROVIDERS: file
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'
      CONNECT_KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'https://ssl-schema-registry:8082'
      CONNECT_KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "sr:sr-secret"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'https://ssl-schema-registry:8082'
      CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "sr:sr-secret"
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'ssl-connect'
      CONNECT_REST_EXTENSION_CLASSES: 'org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension'
      CONNECT_PLUGIN_PATH: /etc/kafka-connect/jars,/usr/share/confluent-hub-components,/usr/share/java,/usr/share/filestream-connectors
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/kafka-connect/secrets/connect_jaas.conf
        -javaagent:/opt/jmx_prometheus/jmx_prometheus_javaagent.jar=7071:/opt/jmx_prometheus/connect-config.yml
