#!/bin/bash

if [ $# -eq 0 ]; then
  echo "usage: $0 <username>"
  exit
fi

USER=$1
shift

PASSWD="$USER-secret"

echo ""
echo "creating user=$USER with password=$PASSWD"
echo ""

kafka-configs \
  --bootstrap-server sasl-broker-1:9092 \
  --command-config ./config/admin-plaintext.config \
  --alter \
  --add-config "SCRAM-SHA-512=[password=${PASSWD}]" \
  --entity-type users \
  --entity-name $USER

echo ""
