#!/bin/sh

kafka-console-consumer \
  --bootstrap-server sasl-broker-1:9092,sasl-broker-2:9092,sasl-broker-3:9092 \
  --consumer.config ./config/admin-plaintext.config \
  --from-beginning \
  --topic "$@"

